// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file booking.proto (package booking, syntax proto3)
/* eslint-disable */

import type { Message } from "@bufbuild/protobuf";
import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file booking.proto.
 */
export const file_booking: GenFile =
	/*@__PURE__*/
	fileDesc(
		"Cg1ib29raW5nLnByb3RvEgdib29raW5nIkcKDkJvb2tpbmdSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkSEAoIaG90ZWxfaWQYAiABKAkSEgoKcHJvbW9fY29kZRgDIAEoCSKRAQoPQm9va2luZ1Jlc3BvbnNlEgoKAmlkGAEgASgJEg8KB3VzZXJfaWQYAiABKAkSEAoIaG90ZWxfaWQYAyABKAkSEgoKcHJvbW9fY29kZRgEIAEoCRIYChBkaXNjb3VudF9wZXJjZW50GAUgASgBEg0KBXByaWNlGAYgASgBEhIKCmNyZWF0ZWRfYXQYByABKAkiJQoSQm9va2luZ0xpc3RSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkiQQoTQm9va2luZ0xpc3RSZXNwb25zZRIqCghib29raW5ncxgBIAMoCzIYLmJvb2tpbmcuQm9va2luZ1Jlc3BvbnNlMp8BCg5Cb29raW5nU2VydmljZRJCCg1DcmVhdGVCb29raW5nEhcuYm9va2luZy5Cb29raW5nUmVxdWVzdBoYLmJvb2tpbmcuQm9va2luZ1Jlc3BvbnNlEkkKDExpc3RCb29raW5ncxIbLmJvb2tpbmcuQm9va2luZ0xpc3RSZXF1ZXN0GhwuYm9va2luZy5Cb29raW5nTGlzdFJlc3BvbnNlQjwKGWNvbS5ob3RlbGlvLnByb3RvLmJvb2tpbmdCDEJvb2tpbmdQcm90b1ABWg9ib29raW5nLXNlcnZpY2ViBnByb3RvMw",
	);

/**
 * Запрос на создание бронирования
 *
 * @generated from message booking.BookingRequest
 */
export type BookingRequest = Message<"booking.BookingRequest"> & {
	/**
	 * @generated from field: string user_id = 1;
	 */
	userId: string;

	/**
	 * @generated from field: string hotel_id = 2;
	 */
	hotelId: string;

	/**
	 * optional
	 *
	 * @generated from field: string promo_code = 3;
	 */
	promoCode: string;
};

/**
 * Describes the message booking.BookingRequest.
 * Use `create(BookingRequestSchema)` to create a new message.
 */
export const BookingRequestSchema: GenMessage<BookingRequest> = /*@__PURE__*/ messageDesc(file_booking, 0);

/**
 * Ответ при создании бронирования
 *
 * @generated from message booking.BookingResponse
 */
export type BookingResponse = Message<"booking.BookingResponse"> & {
	/**
	 * @generated from field: string id = 1;
	 */
	id: string;

	/**
	 * @generated from field: string user_id = 2;
	 */
	userId: string;

	/**
	 * @generated from field: string hotel_id = 3;
	 */
	hotelId: string;

	/**
	 * @generated from field: string promo_code = 4;
	 */
	promoCode: string;

	/**
	 * @generated from field: double discount_percent = 5;
	 */
	discountPercent: number;

	/**
	 * @generated from field: double price = 6;
	 */
	price: number;

	/**
	 * ISO-8601
	 *
	 * @generated from field: string created_at = 7;
	 */
	createdAt: string;
};

/**
 * Describes the message booking.BookingResponse.
 * Use `create(BookingResponseSchema)` to create a new message.
 */
export const BookingResponseSchema: GenMessage<BookingResponse> = /*@__PURE__*/ messageDesc(file_booking, 1);

/**
 * Запрос на получение списка бронирований по userId
 *
 * @generated from message booking.BookingListRequest
 */
export type BookingListRequest = Message<"booking.BookingListRequest"> & {
	/**
	 * @generated from field: string user_id = 1;
	 */
	userId: string;
};

/**
 * Describes the message booking.BookingListRequest.
 * Use `create(BookingListRequestSchema)` to create a new message.
 */
export const BookingListRequestSchema: GenMessage<BookingListRequest> = /*@__PURE__*/ messageDesc(file_booking, 2);

/**
 * Ответ со списком бронирований
 *
 * @generated from message booking.BookingListResponse
 */
export type BookingListResponse = Message<"booking.BookingListResponse"> & {
	/**
	 * @generated from field: repeated booking.BookingResponse bookings = 1;
	 */
	bookings: BookingResponse[];
};

/**
 * Describes the message booking.BookingListResponse.
 * Use `create(BookingListResponseSchema)` to create a new message.
 */
export const BookingListResponseSchema: GenMessage<BookingListResponse> = /*@__PURE__*/ messageDesc(file_booking, 3);

/**
 * gRPC-сервис бронирования
 *
 * @generated from service booking.BookingService
 */
export const BookingService: GenService<{
	/**
	 * @generated from rpc booking.BookingService.CreateBooking
	 */
	createBooking: {
		methodKind: "unary";
		input: typeof BookingRequestSchema;
		output: typeof BookingResponseSchema;
	};
	/**
	 * @generated from rpc booking.BookingService.ListBookings
	 */
	listBookings: {
		methodKind: "unary";
		input: typeof BookingListRequestSchema;
		output: typeof BookingListResponseSchema;
	};
}> = /*@__PURE__*/ serviceDesc(file_booking, 0);
