replicaCount: 1

image:
  name: booking-service
  tag: latest
  pullPolicy: Always
  repository: booking-service

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  ENABLE_FEATURE_X: "true"

resources:

livenessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3

readinessProbe:
  httpGet:
    path: /ping
    port: 8080
  initialDelaySeconds: 3
  periodSeconds: 3
